services:
  miracle-mysql:
    container_name: miracle-mysql
    image: mariadb:latest
    restart: "always"
    expose:
      - "3306"
    networks:
      - miracle-backend
    volumes:
      - miracle-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MIRACLE_MYSQL_PASSWORD}"
      MYSQL_DATABASE: "miracle-db"
      MYSQL_ROOT_HOST: "%"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      timeout: 2s
      retries: 30
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
  miracle-ssh:
    container_name: miracle-ssh
    image: miracle-ssh:latest
    restart: "always"
    ports:
      - "8888:8888"
    build:
      context: .docker/images/miracle-ssh
      dockerfile: Dockerfile
  miracle-backend:
    container_name: miracle-backend
    image: miracle-backend:latest
    restart: "always"
    ports:
      - "9001:9001"
      - "9002:9002"
      - "454:454"
      - "455:455"
    networks:
      - miracle-backend
    volumes:
      - ./config:/usr/src/app/config
    environment:
      MIRACLE_MYSQL_PASSWORD: "${MIRACLE_MYSQL_PASSWORD}"
    depends_on:
      miracle-mysql:
        condition: service_healthy
    build: 
      context: ./
      dockerfile: .docker/images/miracle-backend/Dockerfile
    tty: yes
volumes:
  slemiracleepy-mysql:
    external: true
networks:
  miracle-backend:
    name: miracle-backend