services:
  miracle-mysql:
    container_name: miracle-mysql
    image: mariadb:latest
    restart: "always"
    ports:
      - "3306:3306"
    networks:
      - miracle-backend
    volumes:
      - miracle-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MIRACLE_MYSQL_PASSWORD}"
      MYSQL_DATABASE: "miracle-db"
      MYSQL_ROOT_HOST: "%"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      timeout: 2s
      retries: 30
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
  miracle-redis:
    container_name: miracle-redis
    image: redis:alpine
    restart: "always"
    ports:
      - "6379:6379"
    networks:
      - miracle-backend
    volumes:
      - .docker/volumes/miracle-redis:/usr/local/etc/redis
      - miracle-redis:/data
    healthcheck:
      test: ["CMD", "redis-cli" ,"ping"]
      timeout: 2s
      retries: 30
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--requirepass", "$MIRACLE_REDIS_PASSWORD"]
  miracle-backend:
    container_name: miracle-backend
    image: miracle-backend:latest
    restart: "always"
    ports:
      - "8000:8000"
      - "8001:8001"
    networks:
      - miracle-backend
    volumes:
      - ./config:/usr/src/app/config
    environment:
      MIRACLE_MYSQL_PASSWORD: "${MIRACLE_MYSQL_PASSWORD}"
      MIRACLE_REDIS_PASSWORD: "${MIRACLE_REDIS_PASSWORD}"
    depends_on:
      miracle-mysql:
        condition: service_healthy
    build: 
      context: ./
      dockerfile: .docker/images/miracle-backend/Dockerfile
    tty: yes
volumes:
  miracle-mysql:
    external: true
  miracle-redis:
    external: true
networks:
  miracle-backend:
    name: miracle-backend